SET AUTOBATCHSEQU=%3
SET AUTOBATCHFINAL=8
SET AUTOBATCHDEST=c:\NOTEXISTENT
SET AUTOBATCHALTPATH=%1
SET AUTOBATCHALTOUTPUTPATH=%2
SET AUTOBATCHNOPROGRESS=no
SET AUTOBATCHFILEEXT=
SET AUTOBATCHNOSUBFOLDERS=no
REM "C:\Program Files (x86)\Adobe\Acrobat DC\Acrobat\Acrobat.exe" /n

%4 /n /h /s /o
